### ISSUE TITLE
"TypeNotFoundException: Namespace is not defined for type org.example.biznet.User" on npm test

### ISSUE THREAD

**Issue by nyetwurk** [Preetam007/hyperledger_composer_file_storage#3]
Pre-commit hook fails on npm test

```
> composer-file-storage-ways@0.0.1 test /home/nyet/src/hyperledger_composer_file_storage
> mocha --recursive

  #org.example.biznet
    ChangeAssetValue()
      1) should change the value property of SampleAsset to newValue

  0 passing (1s)
  1 failing

  1) #org.example.biznet ChangeAssetValue() should change the value property of SampleAsset to newValue:
     TypeNotFoundException: Namespace is not defined for type org.example.biznet.User
      at ModelManager.getType (node_modules/composer-common/lib/modelmanager.js:378:19)
      at Factory.newResource (node_modules/composer-common/lib/factory.js:103:45)
      at Context.it (test/logic.js:91:34)
```

**Comment by nyetwurk** [comment]
in ```modules/v0/users/users-crud.js``` USER_NS is defined as ```org.preetam.composer``` not ```org.example.biznet.User```

If I fix the name space there, it fails with
```
TypeNotFoundException: Type SampleAsset is not defined in namespace org.preetam.composer
```
because ```org.preetam.composer.SampleAsset``` isn't defined anywhere.

Are these unit tests actually supposed to work?
